"""Task 1: does the fixture's declared leakage bias show up as query/gold
lexical overlap, and does retrieval accuracy track it?

`retrieval_queries.json` carries KNOWN_BIAS: "queries were generated BY A MODEL
THAT SAW THE GOLD ITEM'S WORDING ... treat a method's absolute recall as an
upper bound." CHARACTERISATION.md sec 1a argues the opposite -- that the failures
are queries which OMIT the gold's discriminator -- but never measures the
overlap. This script measures it.

No model is loaded. Ranks and correctness are read from the committed
characterisation artifact (out/char_pos_bge-small_ft.json); this script only
adds a lexical statistic per row and cross-tabulates.

    python src/phrase_overlap.py --pos out/char_pos_bge-small_ft.json \
        --fixture retrieval_queries.json --targets out/targets_full.json \
        --out out/fusion_task1_overlap.json

Three overlap ratios are reported per row, all over STOPWORD-STRIPPED content
words of the query (Qc) and of the gold wording (Gc):

    cov_query = |Qc & Gc| / |Qc|   how much of the QUERY is drawn from the gold.
                                   This is the leakage direction: a query that
                                   copied the gold scores high.
    cov_gold  = |Qc & Gc| / |Gc|   how much of the gold the query covers. Always
                                   small here -- queries are 2-5 words, gold
                                   stems are sentences.
    jaccard   = |Qc & Gc| / |Qc | Gc|

`cov_query` is the primary. Two gold-text definitions are carried side by side
because they can disagree:

    doc  = the target's INDEXED text: stem + option (what the encoder actually
           sees). This is the one that matters for retrieval.
    fx   = the fixture row's own `text` field, the roster-normalised gold
           wording the generator was shown.

and two tokenisations:

    raw   = lowercased alphanumeric tokens, stopwords dropped, length >= 2.
    stem  = the same, then a LIGHT suffix normaliser (see light_stem). This is
            NOT Porter: it strips plural -s/-es, -ing, -ed, -ly, -ies->y and a
            few nominalising suffixes, and nothing else. Both are reported so a
            conclusion that depends on the stemmer is visible as such.
"""
from __future__ import annotations

import argparse
import json
import math
import re
from collections import defaultdict
from pathlib import Path

# A standard English stoplist plus the handful of survey-instrument function
# words that appear in nearly every stem ("please", "describe", "following").
# Committed here so the statistic is reproducible rather than described.
STOPWORDS = set("""
a about above after again against all am an and any are aren as at be because
been before being below between both but by can cannot could couldn did didn do
does doesn doing don down during each few for from further had hadn has hasn
have haven having he her here hers herself him himself his how i if in into is
isn it its itself just me more most mustn my myself no nor not now of off on
once only or other ought our ours ourselves out over own same shan she should
shouldn so some such than that the their theirs them themselves then there these
they this those through to too under until up very was wasn we were weren what
when where which while who whom why with won would wouldn you your yours
yourself yourselves s t don ve ll re d m o
please describe following ever your you have has been did do does was were are
is any other another type kind number times time many much often long
""".split())

TOKEN_RE = re.compile(r"[a-z0-9]+")


def light_stem(w: str) -> str:
    """Deliberately conservative suffix normalisation. Not Porter.

    Only the suffixes that actually collide in this corpus: plurals, gerunds,
    past tense, adverbs, and the -tion/-ment/-ance nominalisations that turn a
    survey verb into an analyst's noun ("utilise" / "utilisation").
    """
    if len(w) <= 3:
        return w
    for suf, repl, minlen in (
        ("ies", "y", 5), ("sses", "ss", 6), ("ization", "ize", 8),
        ("isation", "ise", 8), ("ation", "ate", 7), ("ement", "e", 7),
        ("ment", "", 6), ("ance", "", 6), ("ence", "", 6),
        ("ing", "", 6), ("edly", "", 7), ("ed", "", 5), ("ly", "", 5),
        ("es", "", 5), ("s", "", 4),
    ):
        if w.endswith(suf) and len(w) >= minlen:
            return w[: len(w) - len(suf)] + repl
    return w


def content_words(text: str, stem: bool) -> set[str]:
    ws = [w for w in TOKEN_RE.findall((text or "").lower())
          if len(w) >= 2 and w not in STOPWORDS]
    if stem:
        ws = [light_stem(w) for w in ws]
    return {w for w in ws if w and w not in STOPWORDS}


def ratios(q: set[str], g: set[str]) -> dict:
    inter = q & g
    return {
        "cov_query": round(len(inter) / len(q), 4) if q else None,
        "cov_gold": round(len(inter) / len(g), 4) if g else None,
        "jaccard": round(len(inter) / len(q | g), 4) if (q or g) else None,
        "n_query_content": len(q), "n_gold_content": len(g),
        "n_shared": len(inter), "shared": sorted(inter),
    }


# ----------------------------------------------------------------- statistics

def pearson(xs, ys):
    n = len(xs)
    if n < 3:
        return None
    mx, my = sum(xs) / n, sum(ys) / n
    sxy = sum((x - mx) * (y - my) for x, y in zip(xs, ys))
    sxx = sum((x - mx) ** 2 for x in xs)
    syy = sum((y - my) ** 2 for y in ys)
    if sxx <= 0 or syy <= 0:
        return None
    return sxy / math.sqrt(sxx * syy)


def rankdata(v):
    """Average ranks, ties shared -- required for Spearman on tied overlaps."""
    order = sorted(range(len(v)), key=lambda i: v[i])
    r = [0.0] * len(v)
    i = 0
    while i < len(order):
        j = i
        while j + 1 < len(order) and v[order[j + 1]] == v[order[i]]:
            j += 1
        avg = (i + j) / 2 + 1
        for k in range(i, j + 1):
            r[order[k]] = avg
        i = j + 1
    return r


def spearman(xs, ys):
    return pearson(rankdata(xs), rankdata(ys))


def perm_p(xs, ys, stat, iters=20000, seed=20260903):
    """Two-sided permutation p-value for a correlation. No scipy in this venv,
    and the sample (n=56 items) is small enough that an asymptotic p would be
    the wrong tool anyway."""
    import random
    rng = random.Random(seed)
    obs = abs(stat(xs, ys))
    ys2 = list(ys)
    hit = 0
    for _ in range(iters):
        rng.shuffle(ys2)
        s = stat(xs, ys2)
        if s is not None and abs(s) >= obs - 1e-12:
            hit += 1
    return round((hit + 1) / (iters + 1), 5)


def pct(v, p):
    if not v:
        return None
    s = sorted(v)
    return round(s[min(len(s) - 1, int(p * (len(s) - 1) + 0.5))], 4)


def dist(v):
    if not v:
        return {"n": 0}
    return {"n": len(v), "mean": round(sum(v) / len(v), 4),
            "p10": pct(v, 0.10), "p25": pct(v, 0.25), "p50": pct(v, 0.50),
            "p75": pct(v, 0.75), "p90": pct(v, 0.90),
            "min": round(min(v), 4), "max": round(max(v), 4),
            "n_zero": sum(1 for x in v if x == 0)}


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--pos", type=Path, default=Path("out/char_pos_bge-small_ft.json"))
    ap.add_argument("--fixture", type=Path, default=Path("retrieval_queries.json"))
    ap.add_argument("--targets", type=Path, default=Path("out/targets_full.json"))
    ap.add_argument("--out", type=Path, required=True)
    a = ap.parse_args()

    P = json.loads(a.pos.read_text())
    fx = json.loads(a.fixture.read_text())
    T = json.loads(a.targets.read_text())
    targets = T["targets"]
    by_id = {t["target_id"]: t for t in targets}

    frows, prows = fx["queries"], P["rows"]
    if len(frows) != len(prows):
        raise SystemExit(f"fixture {len(frows)} rows vs artifact {len(prows)}")

    rows = []
    for i, (f, p) in enumerate(zip(frows, prows)):
        if f["query"] != p["query"]:
            raise SystemExit(f"row {i} query mismatch -- artifacts are not aligned")
        t = by_id[p["gold_target"]]
        doc_text = f"{t['stem'] or ''} {t['option'] or ''}"
        rec = {
            "row": i, "gold_key": p["gold_key"], "query": f["query"],
            "rank": p["rank"], "correct": bool(p["correct"]),
            "cos_top1": round(p["cos_top1"], 6), "cos_gold": round(p["cos_gold"], 6),
        }
        for tag, stemmed in (("raw", False), ("stem", True)):
            q = content_words(f["query"], stemmed)
            rec[f"doc_{tag}"] = ratios(q, content_words(doc_text, stemmed))
            rec[f"fx_{tag}"] = ratios(q, content_words(f["text"], stemmed))
        rows.append(rec)

    # ---- per-item aggregation: k/4 against mean overlap
    items = defaultdict(list)
    for r in rows:
        items[r["gold_key"]].append(r)
    variants = ["doc_raw", "doc_stem", "fx_raw", "fx_stem"]

    per_item = []
    for key, rs in items.items():
        rec = {"gold_key": key, "n_phrasings": len(rs),
               "k_at1": sum(r["correct"] for r in rs)}
        for v in variants:
            rec[f"mean_{v}_cov_query"] = round(
                sum(r[v]["cov_query"] for r in rs) / len(rs), 4)
        per_item.append(rec)
    per_item.sort(key=lambda d: (-d["k_at1"], d["gold_key"]))

    correlations = {}
    for v in variants:
        xs = [d[f"mean_{v}_cov_query"] for d in per_item]
        ys = [float(d["k_at1"]) for d in per_item]
        rp, rs_ = pearson(xs, ys), spearman(xs, ys)
        correlations[v] = {
            "n_items": len(xs),
            "pearson_r": round(rp, 4) if rp is not None else None,
            "spearman_rho": round(rs_, 4) if rs_ is not None else None,
            "spearman_perm_p_two_sided": perm_p(xs, ys, spearman),
        }
        # row level too
        xr = [r[v]["cov_query"] for r in rows]
        yr = [1.0 if r["correct"] else 0.0 for r in rows]
        rrow = spearman(xr, yr)
        correlations[v]["row_level_spearman_rho"] = round(rrow, 4) if rrow else None
        correlations[v]["row_level_perm_p"] = perm_p(xr, yr, spearman)

    # ---- R@1 by overlap bin (fixed bins AND equal-count quartiles)
    def bin_report(v):
        vals = [(r[v]["cov_query"], r) for r in rows]
        fixed_edges = [(-0.001, 0.0), (0.0, 0.25), (0.25, 0.50),
                       (0.50, 0.75), (0.75, 1.001)]
        fixed = []
        for lo, hi in fixed_edges:
            sub = [r for x, r in vals if lo < x <= hi] if lo >= 0 else \
                  [r for x, r in vals if x == 0.0]
            fixed.append({
                "bin": ("exactly 0" if lo < 0 else f"({lo:.2f}, {hi:.2f}]"),
                "n": len(sub),
                "R@1": round(sum(r["correct"] for r in sub) / len(sub), 4) if sub else None,
                "R@5": round(sum(r["rank"] <= 5 for r in sub) / len(sub), 4) if sub else None,
                "R@10": round(sum(r["rank"] <= 10 for r in sub) / len(sub), 4) if sub else None,
                "rank_p50": sorted(r["rank"] for r in sub)[len(sub) // 2] if sub else None,
            })
        # equal-count quartiles, ties broken by row order (stable)
        srt = sorted(range(len(vals)), key=lambda i: (vals[i][0], i))
        quart = []
        n = len(srt)
        for qi in range(4):
            idx = srt[qi * n // 4:(qi + 1) * n // 4]
            sub = [vals[i][1] for i in idx]
            xs = [vals[i][0] for i in idx]
            quart.append({
                "quartile": qi + 1, "n": len(sub),
                "cov_query_range": [round(min(xs), 4), round(max(xs), 4)],
                "cov_query_mean": round(sum(xs) / len(xs), 4),
                "R@1": round(sum(r["correct"] for r in sub) / len(sub), 4),
                "R@5": round(sum(r["rank"] <= 5 for r in sub) / len(sub), 4),
                "R@10": round(sum(r["rank"] <= 10 for r in sub) / len(sub), 4),
            })
        return {"fixed_bins": fixed, "quartiles": quart}

    bins = {v: bin_report(v) for v in variants}

    # ---- LENGTH CONTROL. cov_query = |Qc & Gc| / |Qc| is mechanically coupled
    # to query length: a 1-content-word query can only score 0.0 or 1.0, and 2-
    # and 3-word queries can only hit {0, .5, 1} and {0, .33, .67, 1}. Short
    # queries are also more ambiguous. So a cov_query gradient could be a length
    # gradient wearing a hat. Three checks:
    #   (a) mean query length per cov_query quartile -- is the confound present?
    #   (b) R@1 by cov_query bin WITHIN each query-length stratum
    #   (c) the same correlations against |Qc & Gc| as an absolute count, which
    #       has the opposite length bias (longer queries can share more words)
    def length_control(v):
        lens = [r[v]["n_query_content"] for r in rows]
        per_quartile_len = []
        srt = sorted(range(len(rows)), key=lambda i: (rows[i][v]["cov_query"], i))
        n = len(srt)
        for qi in range(4):
            idx = srt[qi * n // 4:(qi + 1) * n // 4]
            per_quartile_len.append({
                "quartile": qi + 1,
                "mean_query_content_words": round(
                    sum(lens[i] for i in idx) / len(idx), 3)})
        strat = []
        for lo, hi, name in ((1, 2, "1-2 words"), (3, 3, "3 words"),
                             (4, 9, "4+ words")):
            sub = [r for r in rows if lo <= r[v]["n_query_content"] <= hi]
            cells = []
            for blo, bhi, bname in ((-0.01, 0.0, "0"), (0.0, 0.5, "(0, 0.5]"),
                                    (0.5, 1.01, "(0.5, 1.0]")):
                s = [r for r in sub if blo < r[v]["cov_query"] <= bhi] if blo >= 0 \
                    else [r for r in sub if r[v]["cov_query"] == 0.0]
                cells.append({"cov_query_bin": bname, "n": len(s),
                              "R@1": round(sum(r["correct"] for r in s) / len(s), 4)
                              if s else None})
            strat.append({"query_length": name, "n": len(sub),
                          "R@1": round(sum(r["correct"] for r in sub) / len(sub), 4)
                          if sub else None,
                          "by_cov_query": cells})
        xs = [float(r[v]["n_shared"]) for r in rows]
        ys = [1.0 if r["correct"] else 0.0 for r in rows]
        rho_abs = spearman(xs, ys)
        xl = [float(l) for l in lens]
        rho_len = spearman(xl, ys)
        rho_len_cov = spearman(xl, [r[v]["cov_query"] for r in rows])
        return {
            "mean_query_length_per_cov_quartile": per_quartile_len,
            "spearman_query_length_vs_cov_query": round(rho_len_cov, 4)
            if rho_len_cov is not None else None,
            "spearman_query_length_vs_correct": round(rho_len, 4)
            if rho_len is not None else None,
            "spearman_abs_shared_words_vs_correct": round(rho_abs, 4)
            if rho_abs is not None else None,
            "abs_shared_perm_p": perm_p(xs, ys, spearman),
            "stratified_by_query_length": strat,
        }

    length = {v: length_control(v) for v in variants}
    n_doc_fx_differ = sum(
        1 for r in rows if r["doc_stem"]["shared"] != r["fx_stem"]["shared"])

    # ---- overlap distribution, correct vs incorrect top-1
    cvi = {}
    for v in variants:
        cvi[v] = {
            "correct_top1": dist([r[v]["cov_query"] for r in rows if r["correct"]]),
            "incorrect_top1": dist([r[v]["cov_query"] for r in rows if not r["correct"]]),
            "all": dist([r[v]["cov_query"] for r in rows]),
            "blind_spot_items_0of4_and_1of4": dist([
                r[v]["cov_query"] for r in rows
                if sum(x["correct"] for x in items[r["gold_key"]]) <= 1]),
        }

    zero_overlap = [
        {"query": r["query"], "gold_key": r["gold_key"], "rank": r["rank"],
         "gold_stem": (by_id[prows[r["row"]]["gold_target"]]["stem"] or "")[:110]}
        for r in rows if r["doc_stem"]["cov_query"] == 0.0]

    rep = {
        "schema": "compass_phrase_overlap/1",
        "question": ("Is the fixture's declared leakage bias (queries written by a "
                     "model that saw the gold wording) visible as query/gold lexical "
                     "overlap, and does R@1 rise with it?"),
        "interpretation_recorded_before_running": (
            "If R@1 rises monotonically with overlap, leakage is real and "
            "concentrated in the high-overlap rows, and the upper-bound caveat in "
            "retrieval_queries.json::KNOWN_BIAS stands. If R@1 is flat or "
            "non-monotonic across quartiles, the caveat largely dissolves and 0.567 "
            "may be a LOWER bound for a real query stream, since a researcher who "
            "has read the codebook would use more of the instrument's vocabulary, "
            "not less."),
        "model_under_test": P["label"],
        "source_artifact": str(a.pos),
        "fixture": str(a.fixture),
        "fixture_known_bias": fx.get("KNOWN_BIAS"),
        "fixture_generator": fx.get("generator"),
        "dictionary_version_hash": T["dictionary_version_hash"],
        "n_rows": len(rows), "n_items": len(items),
        "recall_at1_reproduced": P["recall_at1"],
        "tokenisation": {
            "content_words": "lowercased [a-z0-9]+ tokens, len>=2, stoplist below",
            "stopwords_n": len(STOPWORDS),
            "raw": "no stemming",
            "stem": "light suffix normaliser (light_stem in this file); NOT Porter",
            "gold_text_doc": "target stem + option -- the text the encoder indexes",
            "gold_text_fx": "the fixture row's own `text` field (gold wording shown "
                            "to the query generator)",
            "primary_metric": "cov_query = |Qc & Gc| / |Qc|",
        },
        "doc_vs_fx_gold_text": {
            "n_rows_where_content_sets_differ": n_doc_fx_differ,
            "note": ("The fixture's `text` field and the target's indexed "
                     "stem+option are the same wording for most rows, so the two "
                     "gold-text definitions agree to 3 decimal places on every "
                     "aggregate below. Both are kept as a cross-check."),
        },
        "correlations_overlap_vs_accuracy": correlations,
        "recall_by_overlap_bin": bins,
        "length_confound_control": length,
        "overlap_distribution": cvi,
        "rows_with_zero_overlap_doc_stem": zero_overlap,
        "per_item": per_item,
        "rows": rows,
    }
    a.out.write_text(json.dumps(rep, indent=1))

    v = "doc_stem"
    print(f"{P['label']}  n={len(rows)} rows / {len(items)} items  "
          f"R@1 {P['recall_at1']}")
    print(f"  primary variant {v} (indexed stem+option, light-stemmed)")
    d = cvi[v]
    print(f"  cov_query  all      mean {d['all']['mean']}  p50 {d['all']['p50']}  "
          f"zeros {d['all']['n_zero']}/{d['all']['n']}")
    print(f"             correct  mean {d['correct_top1']['mean']}  p50 {d['correct_top1']['p50']}")
    print(f"             wrong    mean {d['incorrect_top1']['mean']}  p50 {d['incorrect_top1']['p50']}")
    print(f"             0/4+1/4  mean {d['blind_spot_items_0of4_and_1of4']['mean']}")
    c = correlations[v]
    print(f"  item-level  rho {c['spearman_rho']} (perm p {c['spearman_perm_p_two_sided']})"
          f"   r {c['pearson_r']}")
    print(f"  row-level   rho {c['row_level_spearman_rho']} (perm p {c['row_level_perm_p']})")
    print("  R@1 by cov_query quartile:")
    for q in bins[v]["quartiles"]:
        print(f"    Q{q['quartile']}  cov {q['cov_query_range'][0]:.2f}-"
              f"{q['cov_query_range'][1]:.2f} (mean {q['cov_query_mean']:.3f})  "
              f"n={q['n']}  R@1 {q['R@1']}  R@10 {q['R@10']}")
    L = length[v]
    print(f"  length confound: rho(len, cov_query) "
          f"{L['spearman_query_length_vs_cov_query']}  "
          f"rho(len, correct) {L['spearman_query_length_vs_correct']}  "
          f"rho(|shared|, correct) {L['spearman_abs_shared_words_vs_correct']} "
          f"(p {L['abs_shared_perm_p']})")
    for s in L["stratified_by_query_length"]:
        cells = "  ".join(f"{c['cov_query_bin']}: {c['R@1']} (n={c['n']})"
                          for c in s["by_cov_query"])
        print(f"    {s['query_length']:<10} n={s['n']:<4} R@1 {s['R@1']}   {cells}")
    print(f"-> {a.out}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
